secret_key_base:
devise_jwt_secret_key:

development:
  database:
    database:
    username:
    password:
    host:
    port:


test:
  database:
    database:
    username:
    password:
    host:
    port:
